version: '3'

services:
  core:
    restart: always
    image: 'ghcr.io/event-cell/core:main'
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: "${CORE_DATA}"
        target: /data
      - type: bind
        source: "${TIMING_DB}"
        target: /app/prisma/Events
        read_only: true
