-- CreateTable
CREATE TABLE "RECORDS" (
    "IDX" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CLASS" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "CAR" TEXT NOT NULL,
    "TIME" REAL NOT NULL,
    "DATE_SET" DATETIME NOT NULL,
    "EVENT_ID" INTEGER NOT NULL,
    "LAPS" INTEGER NOT NULL
);
