name: Build Nightly

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # TODO: Testing

  build:
    name: Build for production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Generate Prisma clients
        run: cd server && yarn prismaGenerate

      - name: Build
        run: yarn build

      - name: Verify build output
        run: |
          echo "Server build output:"
          ls -la server/dist/
          echo "Server dist/server:"
          ls -la server/dist/server/
          echo "Node modules:"
          ls -la node_modules/ | head -10
          echo "Node modules size:"
          du -sh node_modules/

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            server/dist
            node_modules

  docker:
    name: Build Docker File
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Display structure of downloaded files
        run: |
          echo "Root directory:"
          ls -la
          echo "Server dist:"
          ls -la server/dist/
          echo "Node modules:"
          ls -la node_modules/ | head -10

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/event-cell/core:main
          cache-from: type=gha
          cache-to: type=gha,mode=max


