name: Mirror
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'event-cell/core'
          source_branch: 'main'
          destination_repo: 'sdmatech/core-mirror'
          destination_branch: 'main'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
